name: Basic CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify files
        run: |
          test -f index.html
          test -f style.css
          test -f app.js

      - name: Success
        run: echo "Project checked successfully"
